
import "@/styles/globals.css";
import Footer from "@/components/molecules/footer/footer";
import CookieConsent from "@/components/elements/cookieConsent/cookieConsent";


export const metadata = {
  title: "Que Visitar en Cataluña",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="scroll-smooth">
      <body>
        <main>{children}</main>
        <CookieConsent />
        <Footer />
      </body>
    </html>
  );
}
